name: "Phd_DataModeling"
services:
  
  #redis:
  #  image: "redis/redis-stack:latest"
  #  ports:
  #    - "6379:6379"
  #    - "8002:8001"
  #  volumes:
  #    - ./data:/data

  neo4j:
    image: "neo4j:community"
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./data/neo4j:/data
